<?php

return [
	'primary'         => [ 'color' => \get_theme_mod( 'color_primary',   '687d81' ) ],
	'secondary'       => [ 'color' => \get_theme_mod( 'color_secondary', 'e3342f' ) ],
	'black'           => [],
	'white'           => [],
	'gray-darkest'    => [],
	'gray-darker'     => [],
	'gray-dark'       => [],
	'gray'            => [],
	'gray-light'      => [],
	'gray-lighter'    => [],
	'gray-lightest'   => [],
	'red-darkest'     => [],
	'red-darker'      => [],
	'red-dark'        => [],
	'red'             => [],
	'red-light'       => [],
	'red-lighter'     => [],
	'red-lightest'    => [],
	'orange-darkest'  => [],
	'orange-darker'   => [],
	'orange-dark'     => [],
	'orange'          => [],
	'orange-light'    => [],
	'orange-lighter'  => [],
	'orange-lightest' => [],
	'yellow-darkest'  => [],
	'yellow-darker'   => [],
	'yellow-dark'     => [],
	'yellow'          => [],
	'yellow-light'    => [],
	'yellow-lighter'  => [],
	'yellow-lightest' => [],
	'green-darkest'   => [],
	'green-darker'    => [],
	'green-dark'      => [],
	'green'           => [],
	'green-light'     => [],
	'green-lighter'   => [],
	'green-lightest'  => [],
	'blue-darkest'    => [],
	'blue-darker'     => [],
	'blue-dark'       => [],
	'blue'            => [],
	'blue-light'      => [],
	'blue-lighter'    => [],
	'blue-lightest'   => []
];
