<?php

return [
	'a.co'            => 'amazon',
	'amazon.com'      => 'amazon',
	'behance.net'     => 'behance',
	'codepen.io'      => 'codepen',
	'deviantart.com'  => 'deviantart',
	'digg.com'        => 'digg',
	'dribbble.com'    => 'dribbble',
	'dropbox.com'     => 'dropbox',
	'facebook.com'    => 'facebook',
	'feed'            => 'rss-square-solid',
	'flickr.com'      => 'flickr',
	'foursquare.com'  => 'foursquare',
	'getpocket.com'   => 'get',
	'github.com'      => 'github',
	'plus.google.com' => 'google',
	'instagram.com'   => 'instagram',
	'linkedin.com'    => 'linkedin',
	'mailto:'         => 'envelope-open-regular',
	'medium.com'      => 'medium',
	'pinterest.com'   => 'pinterest',
	'reddit.com'      => 'reddit',
	'skype.com'       => 'skype',
	'skype:'          => 'skype',
	'slideshare.net'  => 'slideshare',
	'snapchat.com'    => 'snapchat',
	'soundcloud.com'  => 'soundcloud',
	'spotify.com'     => 'spotify',
	'stumbleupon.com' => 'stumbleupon',
	'tumblr.com'      => 'tumblr',
	'twitch.tv'       => 'twitch',
	'twitter.com'     => 'twitter',
	'vimeo.com'       => 'vimeo',
	'vine.co'         => 'vine',
	'vk.com'          => 'vk',
	'wordpress.org'   => 'wordpress',
	'wordpress.com'   => 'wordpress',
	'yelp.com'        => 'yelp',
	'youtube.com'     => 'youtube'
];
