<!-- wp:image {"align":"wide","id":4167,"sizeSlug":"exhale-landscape-xl","linkDestination":"none","className":"is-style-caption-overlay"} -->
<figure class="wp-block-image alignwide size-exhale-landscape-xl is-style-caption-overlay"><img src="http://localhost/wp-content/uploads/2021/05/pexels-pixabay-46254-1366x768.jpg" alt="" class="wp-image-4167"/><figcaption>Lorem ipsum dolor</figcaption></figure>
<!-- /wp:image -->

<!-- wp:gallery {"ids":[4365,4364,4362],"linkTo":"none","sizeSlug":"exhale-square-medium","align":"wide"} -->
<figure class="wp-block-gallery alignwide columns-3 is-cropped"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-skyler-ewing-5952171-640x640.jpg" alt="" data-id="4365" data-full-url="http://localhost/wp-content/uploads/2021/05/pexels-skyler-ewing-5952171.jpg" data-link="http://localhost/block-testing-10/pexels-skyler-ewing-5952171/" class="wp-image-4365"/><figcaption class="blocks-gallery-item__caption">Lorem ipsum dolor</figcaption></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-chris-f-6025023-640x640.jpg" alt="" data-id="4364" data-full-url="http://localhost/wp-content/uploads/2021/05/pexels-chris-f-6025023-scaled.jpg" data-link="http://localhost/block-testing-10/pexels-chris-f-6025023/" class="wp-image-4364"/><figcaption class="blocks-gallery-item__caption">Lorem ipsum dolor</figcaption></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-rajukhan-pathan-5895958-640x640.jpg" alt="" data-id="4362" data-full-url="http://localhost/wp-content/uploads/2021/05/pexels-rajukhan-pathan-5895958-scaled.jpg" data-link="http://localhost/block-testing-10/pexels-rajukhan-pathan-5895958/" class="wp-image-4362"/><figcaption class="blocks-gallery-item__caption">Lorem ipsum dolor</figcaption></figure></li></ul></figure>
<!-- /wp:gallery -->

<!-- wp:image {"align":"wide","id":4167,"sizeSlug":"exhale-landscape-xl","linkDestination":"none","className":"is-style-caption-overlay"} -->
<figure class="wp-block-image alignwide size-exhale-landscape-xl is-style-caption-overlay"><img src="http://localhost/wp-content/uploads/2021/05/pexels-pixabay-46254-1366x768.jpg" alt="" class="wp-image-4167"/><figcaption>Lorem ipsum dolor</figcaption></figure>
<!-- /wp:image -->
