<!-- wp:group {"align":"full","style":{"spacing":{"padding":{"left":"0px","right":"0px","top":"32px","bottom":"32px"}}},"backgroundColor":"gray-100"} -->
<div class="wp-block-group alignfull has-gray-100-background-color has-background" style="padding-top:32px;padding-right:0px;padding-bottom:32px;padding-left:0px"><!-- wp:group {"layout":{"inherit":true}} -->
<div class="wp-block-group"><!-- wp:heading {"style":{"typography":{"textTransform":"uppercase"}},"textColor":"gray-900","className":"my-0","fontSize":"extra-large"} -->
<h2 class="my-0 has-gray-900-color has-text-color has-extra-large-font-size" style="text-transform:uppercase">Project Name</h2>
<!-- /wp:heading --></div>
<!-- /wp:group -->

<!-- wp:gallery {"ids":[3497,3498,3499,3500,3501,3502],"linkTo":"none","align":"full","className":"is-style-default"} -->
<figure class="wp-block-gallery alignfull columns-3 is-cropped is-style-default"><ul class="blocks-gallery-grid"><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-ylanite-koppens-810036-1024x682.jpg" alt="" data-id="3497" data-link="http://localhost/?attachment_id=3497" class="wp-image-3497"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-sharon-mccutcheon-1148496-1024x683.jpg" alt="" data-id="3498" data-link="http://localhost/?attachment_id=3498" class="wp-image-3498"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-iconcom-226591-1024x768.jpg" alt="" data-id="3499" data-link="http://localhost/?attachment_id=3499" class="wp-image-3499"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-sharon-mccutcheon-3679411-1024x683.jpg" alt="" data-id="3500" data-link="http://localhost/?attachment_id=3500" class="wp-image-3500"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-sharon-mccutcheon-4219312-1024x683.jpg" alt="" data-id="3501" data-link="http://localhost/?attachment_id=3501" class="wp-image-3501"/></figure></li><li class="blocks-gallery-item"><figure><img src="http://localhost/wp-content/uploads/2021/05/pexels-steve-johnson-1629817-1024x683.jpg" alt="" data-id="3502" data-full-url="http://localhost/wp-content/uploads/2021/05/pexels-steve-johnson-1629817.jpg" data-link="http://localhost/?attachment_id=3502" class="wp-image-3502"/></figure></li></ul><figcaption class="blocks-gallery-caption">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</figcaption></figure>
<!-- /wp:gallery --></div>
<!-- /wp:group -->
